DROP TABLE IF EXISTS mentorships CASCADE;
DROP TABLE IF EXISTS experience CASCADE;
DROP TABLE IF EXISTS mentor_expertise CASCADE;
DROP TABLE IF EXISTS expertise CASCADE;
DROP TABLE IF EXISTS mentors CASCADE;
DROP TABLE IF EXISTS startups CASCADE;
DROP TABLE IF EXISTS users CASCADE;
